[package]
name = "qh210521"
version = "0.1.0"
authors = ["vadim"]
edition = "2018"

[dependencies]
rocket = {path = "../Rocket/core/lib"}
rocket_contrib = {path = "../Rocket/contrib/lib"}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

rand = "0.8"